### ISSUE TITLE
Major FPS drop with retextured heads

### ISSUE THREAD

**Issue by 54M44R** [SHsuperCM/CITResewn#132]
Retextured heads in CIT Resewn leads to substantial fps drops.

CIT Resewn 1.0.1+1.18.2

In the image below, all these items (excluding two) are heads that have been retextured. 

![unknown (3)](https://user-images.githubusercontent.com/26176694/163860446-9def33b3-2bb9-4bc1-9490-91ea80706961.png)

Running the resourcepack under Optifine yields ~ 80 fps in this inventory, while under CIT Resewn yields ~ 20 fps. 

I am not sure as to what the difference is between Optifine and Resewn's implementation of rendering retextured heads, but it seems that Resewn's implementation is not efficient enough to handle heads.

**Comment by SHsuperCM** [comment]
Can you send the resourcepack and a list of head items that cause this?

**Comment by 54M44R** [comment]
Absolutely

[Slimefun-Beautified-Light_v1.0.zip](https://github.com/SHsuperCM/CITResewn/files/8512861/Slimefun-Beautified-Light_v1.0.zip)

This is a Slimefun resourcepack so you'd need Slimefun to test the heads. As for a list I dont have one on hand and cannot get one at the moment.

**Comment by SHsuperCM** [comment]
The pack is just very expensive to run because of the amount of checks the CITs perform.
Luckily I predicted such a pack would exist so there's a fix!

Assuming you have both Mod Menu and Cloth Config.
Go to `Esc/Main Menu > Mods > CIT Resewn > Configure` and raise the cache time to whatever works best for you, after raising it on my end I noticed the fps drops were gone when I opened an inventory with a lot of retextured heads.

This will however make certain CITs take a tiny bit longer to update on the item but it shouldn't be that bad depending on how high the cache time is set.
