### ISSUE TITLE
[question] How to specify armor texture layer for all types

### ISSUE THREAD

**Issue by DearFox** [SHsuperCM/CITResewn#158]
Based on what is said here: https://github.com/SHsuperCM/CITResewn/issues/39
I have to set the texture path for each armor material:
texture.leather_layer_1=jarl_layer_1
texture.iron_layer_1=jarl_layer_1
texture.diamond_layer_1=jarl_layer_1

but is there any easier way? Since I change the texture for all possible armor elements from any materials.
(matchItems=leather_helmet chainmail_helmet iron_helmet golden_helmet diamond_helmet netherite_helmet turtle_helmet
and so on for each piece of armor)
![image](https://user-images.githubusercontent.com/59219907/173006541-7a193845-325e-46fe-ba86-57a38dee3838.png)
and in the case of leather armor elements, I get clearly not what I would like.

and specifying the texture for each armor material, I will simply duplicate the same text, just changing the names of the material, which is very inconvenient and will make the resource pack heavier, which is critical when used as a server resource pack.

**Comment by SHsuperCM** [comment]
Currently there isn't a way to use the arbitrary textures for the armor type because of how the type was defined in MCPatcher.

To keep parity you'd have to specify the textures you'd like to change manually.

And as I said in #39
> Simpler declaration support is planned 

this is something I already have planned in the [Future Plans column on the project board](https://github.com/SHsuperCM/CITResewn/projects/1#card-76149278).
