### ISSUE TITLE
Compatibility with Cosmetic Armor Fabric

### ISSUE THREAD

**Issue by Alkiasan** [SHsuperCM/CITResewn#17]
When used alongside https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric , CIT armor used in cosmetic slots doesn't appear as its CIT, and instead appears as its default item, is this possible to add compat for?

**Comment by SHsuperCM** [comment]
Added explicit support in v0.5.2
https://modrinth.com/mod/cit-resewn/version/na5V4QuI

**Comment by SHsuperCM** [comment]
Broke support with the v1 rewrite

**Comment by Alkiasan** [comment]
was about to report this lol gj catching it! Hope it's fixed soon!

**Comment by Alkiasan** [comment]
Is this still planned? Noticed it was removed from the to-do. Testing with the VanitySlots mod on 1.18.2 and the issue still persists.

**Comment by SHsuperCM** [comment]
I'm not sure anymore, haven't decided. Right now I'm leaning towards providing an api for these mods to put their own support when they make these types of slots.

It was removed because there were other pressing things in the todo and that todo column is for the next release so these issues were removed until I decided what I'm going to do with it.

**Comment by SHsuperCM** [comment]
Aight. As much as I want to add support from CIT Resewn's side, I have decided it'd be better not to for now. 
These mods will have to add support on their side and so there is now an api to facilitate that.

**Comment by NyakoFox** [comment]
Hello, I was wondering if there was a usage example of this somewhere? I'd like to add support in my mod but can't figure out how to use the API that was added for this.
