### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by RoonMoonlight** [SHsuperCM/CITResewn#218]
Does this mod requires update to 1.19.3? if not please mark it as 1.19.3 compatible on CurseForge and Modrinth.

**Comment by SHsuperCM** [comment]
Most mods will require updating every minor version now since the junk that mojang decided to do this update.

I'll leave this issue open until the mod is updated but it should take a bit.

**Comment by SenTony** [comment]
Can you update this mod some faster?

**Comment by RoonMoonlight** [comment]
> Can you update this mod some faster?

Patience is key bro. They are working on it so wait a little more

**Comment by SHsuperCM** [comment]
So update for today: 
There is a "working" version in the 1.19.3 branch but it's missing a very important feature which is the ability to load textures from outside of the standardized vanilla models. Releasing it in this state will break a lot of packs who store the texture next to the cit or outside of the default textures directories.
If you know what you are doing feel free to compile the 1.19.3 branch and it should load packs with cits that specify models explicitly and do the folders like they are in vanilla. If not, it's gonna take a while longer until I find a solution and even then it'd be a gross workaround.

If anyone has any ideas for working around this to allow old packs to load, please let me know.

<br>
@SenTony I would love to see you try and update if you think it's that easy. Please, go ahead. We are waiting  :/

**Comment by SenTony** [comment]
@SHsuperCM   I'm don't think that updating is easy! I'm just playing on a server with my modpack and the server just updated to 1.19.3! I wanna to update modpack and this beautiful and unbelievable mod also in my modpack! To sum it up - Sorry!

**Comment by Disguys** [comment]
@YoungSoulluoS sorry to interrupt, but you already have experience working on CEM, could you help with this question for CITResewn?

**Comment by YoungSoulluoS** [comment]
> @YoungSoulluoS sorry to interrupt, but you already have experience working on CEM, could you help with this question for CITResewn? 😊

I'm not good at coding. It's not the same thing to refine what's ready and create it from scratch. Well, I'll have a look for interest.

**Comment by YoungSoulluoS** [comment]
Maybe the author of CIT should have a look at the CEM code and how textures and models are loaded there.

**Comment by unit-a-user** [comment]
Let's I do it later, I currently so busy. I had plans for port this mod into snapshots (currently known as 1.19.3).

**Comment by SHsuperCM** [comment]
I think I found a way around the atlas bullshit but it's not elegant for current code and it still has a few broken things in it. Gonna need to do some more testing.

@YoungSoulluoS 
> Maybe the author of CIT should have a look at the CEM code and how textures and models are loaded there.
> 
> https://github.com/dorianpb/cem

Sadly [dorianpb/cem](https://github.com/dorianpb/cem) has nothing yet that tackles the issues I'm facing with 1.19.3.

@unit-a-user 
> Let's I do it later, I currently so busy. I had plans for port this mod into snapshots (currently known as 1.19.3).

I just saw the PR, thank you for your work but the 1.19.3 branch is already ahead of it. (closing the pr)

**Comment by HarvelsX** [comment]
> I think I found a way around the atlas bullshit but it's not elegant for current code and it still has a few broken things in it. Gonna need to do some more testing.

@SHsuperCM, why bypass it when you can join it ![Jokerge](https://cdn.7tv.app/emote/6306876cbe8c19d70f9d6b22/1x.webp "Jokerge")? Just create your own atlases.

**Comment by SHsuperCM** [comment]
@HarvelsX 
> @SHsuperCM, why bypass it when you can join it ![Jokerge](https://camo.githubusercontent.com/008a0a653af4b2559162d4730f8b6772aabb5ed06fd853c1e85a50012ba2c469/68747470733a2f2f63646e2e3774762e6170702f656d6f74652f3633303638373663626538633139643730663964366232322f31782e77656270)? Just create your own atlases.

Whoops, sorry, I didn't mean bypass it as in not use it. I meant I found a way to add textures to the same "blocks" atlas that items use normally (also using paths I tell it to use). Right now what's still buggy is figuring out how to select the textures properly because there are some instances where adding the textures in the `/cit/` directories is not enough and even if it was, it's against the performance increase that mojang wanted to achieve.

**Comment by HarvelsX** [comment]
> there are some instances where adding the textures in the `/cit/` directories

@SHsuperCM, I think we should put the resource pack creators in some kind of frame of reference here, as well as ask them NOT to use broken IDs.
Mojang is trying to create some sort of standard for resource packs, and it would be nice to integrate mods into their ecosystem.

https://github.com/HarvelsX/Continuity/blob/323c77e0c475413a2da97f64a05419f5a5105827/src/main/java/me/pepperbell/continuity/client/mixin/AtlasLoaderMixin.java

Above I just add a custom atlas source, but would like to coordinate a common atlas source for the optifine directory.
I would like to know your proposal for a solution to this problem.

**Comment by SHsuperCM** [comment]
@HarvelsX 

Asking resourcepack creators to adhere to a standard isn't a viable solution as long as optifine is alive. People will always come in and complain that something is working on optifine but isn't on our mods. We should definitely advocate for it but we cannot rely on them listening. This is the reason I made broken paths something people must opt into, that way new pack creators are aware that it's just an extra unnecessary step that users would have to do.

What I'm going for with CIT Resewn is supporting (**\*some\***) legacy stuff to allow some packs to work without much change. If we know already that, for example, certain cits are adding certain textures, it would be simpler to solve custom texture paths on the mod's side, rather than the pack creators'.

> Above I just add a custom atlas source, but would like to coordinate a common atlas source for the optifine directory.

That's what I recently figured to do as well. For now I just added the `assets/ROOT/cit` directories(and their subdirectories) to the blocks atlas as well, I believe the next step for CIT Resewn would be to do something a little more clever than that to only add requested textures but I need to do more research and testing.

If you ask me, I'd say I'm against creating a common atlas source for the optifine directory as the whole purpose of the atlas change in 1.19.3 was to load resource packs faster which we would go against by adding the entire "optifine" directory or related directories. At that point it would be much clearer for pack creators if we just let them specify atlas sources(like mojang is doing).

**Comment by LangKeWAVE** [comment]
good luck

**Comment by vsecoder** [comment]
Really looking forward...

**Comment by SHsuperCM** [comment]
Okay I need to do a little more bug testing, cleanup and look at some PRs but expect a 1.19.3 version within the next day if everything goes right.

**Comment by MendingNights** [comment]
> Okay I need to do a little more bug testing, cleanup and look at some PRs but expect a 1.19.3 version within the next day if everything goes right.

That's great news!  Thanks for your efforts.

**Comment by SHsuperCM** [comment]
# \o/

v1.1.3 is out for mc 1.19.3!
Remember to open an issue if you encounter any bugs!
