### ISSUE TITLE
Cosmetic Armor Support doesn't support Elytras in Cosmetic Slots

### ISSUE THREAD

**Issue by Alkiasan** [SHsuperCM/CITResewn#23]
Thanks for taking the time to add cosmetic armor support!

As title states though, Elytras don't seem to work with it... Is it possible to fix this?

Examples:
If nothing is in the main slot, but an elytra is in the cosmetic slot, nothing appears.
If an elytra is in the main slot, and the CIT elytra is in the cosmetic slot, it appears.
If a chestplate is in the main slot, and a CIT elytra is in the cosmetic slot, nothing appears, or sometimes, the Elytra will display but without the CIT

**Comment by SHsuperCM** [comment]
> If an elytra is in the main slot, and the CIT elytra is in the cosmetic slot, it appears.

One of the only things I actually tested when I added support initially.

> If nothing is in the main slot, but an elytra is in the cosmetic slot, nothing appears.

Cosmetic Armor bug, the same happens without cit resewn. The `ElytraFeatureRenderer` does nothing if the item equipped in the equipment slot is not an elytra. You can see this happening with a chestplate in the equipment slot and a normal elytra in the cosmetic slot.

> If a chestplate is in the main slot, and a CIT elytra is in the cosmetic slot, nothing appears

Caused by the same bug as the one above.

> or sometimes, the Elytra will display but without the CIT

Fixed in bfa600f
