### ISSUE TITLE
CIT pack not working

### ISSUE THREAD

**Issue by Pubbs-TheClown** [SHsuperCM/CITResewn#231]
For the life of me I cannot get the maeflower cit pack (https://www.planetminecraft.com/texture-pack/maeflowers-cit-pack/) to work. I've tried everything I could think of and can't figure out if its the pack itself or if its just plain not compatible for one reason or another. I've even tried comparing to other CIT pack such as moondrop, minituria, and mizunous and found that the json files and properties are nearly identical with only some differences. Im new to this whole cit pack thing with resewn so perhaps it was something I overlooked but its driving me insane, mainly not knowing if its a problem with the pack or citresewn...

**Comment by dbrighthd** [comment]
Hey the problem seems to be with the pack itself, many of its files contain spaces which is not supported (only supported with optifine because of a bug iirc) 

I was able to get the pack to work by going into the CIT resewn settings (through modmenu) and enabling the "Allow broken paths in resourcepacks" option and then restarting minecraft. 

Try this and please let me know if it works!
![image](https://user-images.githubusercontent.com/68525639/215373832-035d4072-d626-46d3-80a0-eb36a711348c.png)

**Comment by Pubbs-TheClown** [comment]
HOLY COW IT WORKED TYSM! I feel stupid cause I thought I had already messed with at setting but didn't apparently, thanks for the help. Now my apartment can have fridges :]
