### ISSUE TITLE
Suggestion: Option to hide item frame nametags

### ISSUE THREAD

**Issue by Viotomix** [SHsuperCM/CITResewn#249]
Would it be possible to add an option to the config to disable namtags from being displayed in itemframes?

I've tried looking for other ways, since I dislike seeing nametags whenever I look at decorations, but I haven't been able to find any so far and this seems like an appropriate place to ask for such a feature.

If its not possible or too far outside of the scope of this mod I understand tho.

**Comment by SHsuperCM** [comment]
Although it *is* possible and should be rather simple, you're right in saying that this is out if scope. Especially as a config option and not as a cit type(with a cit type you'd need to add a case for every custom item in the resourcepack)

One of the planned types is a name modifier so that could possibly be added as an option in there. However, again, you'd need a new properties file for every cit you want this to work on.

What I recommend you do is either make a mod to disable item frame name tags yourself or ask in the requests forum on the fabric discord. This should be insanely easy to implement with one mixin to just disable every item frame's nametags.
