### ISSUE TITLE
Failed to list path /data/minecraft/datapacks/update_1_20/assets

### ISSUE THREAD

**Issue by silentnyte** [SHsuperCM/CITResewn#259]
When creating a new single player world I get the titled error. This is using the following versions and mods.
Prism Launcher version: 6.3
jdk-17.0.5.8-hotspot
CITResewn-1.1.3+1.19.4
fabric-api-0.80.0+1.19.4
Minecraft 1.19.4 with Fabric Loader 0.14.19

**Comment by Madis0** [comment]
Can confirm with broken paths enabled. Does vanilla really use broken paths or is there an issue with the detection?

**Comment by SHsuperCM** [comment]
Seems like a detection issue. But then again, detection only runs when Broken Paths is enabled which it shouldnt be.

I am a little hesitant to look further into this as it's just an issue that is derived from Broken Paths which as warned several times, is unstable and issues that come from it are supposed to not be fixed intentionally.

See if this happens after disabling broken paths and then I could probably reopen this issue but otherwise I'm closing it for now.
