### ISSUE TITLE
Difficulty with compiling

### ISSUE THREAD

**Issue by MithicSpirit** [SHsuperCM/CITResewn#283]
It seems like Modrinth integration is enabled by default when running `./gradle build`, which means that if I do not provide a `TOKEN_MODRINTH` the project fails to build. I believe that a similar issue is also present with Curseforge, although the error from Modrinth triggers first and stops compilation entirely. 

I believe that this can be fixed by either making the integration be a separate command (so it doesn't affect `./gradlew build`) or providing instructions on how to compile this project bypassing this. I used to have a patch I used for disabling Modrinth and Curseforge, but that was back for 1.19 and now that I've gotten around to updating to 1.20 the files have changed sufficiently that the patch no longer applies.

**Comment by SHsuperCM** [comment]
Very intentional, you are not supposed to be compiling if you do not know how to work with gradle. The process depends on running on my machine which is by design. 
If you want to commit PRs or build on your end in general, you could just comment out the publishing sections of the buildscripts:
https://github.com/SHsuperCM/CITResewn/blob/ad5ffa41a5e34c9baf897e9178e6d9b4bd6d3ed8/build.gradle#L63-L114
https://github.com/SHsuperCM/CITResewn/blob/ad5ffa41a5e34c9baf897e9178e6d9b4bd6d3ed8/defaults/build.gradle#L65-L83 
(ofc making sure not to commit the commented out parts)

**Comment by MithicSpirit** [comment]
Yeah this is mainly just for testing newer builds since I like living on the bleeding edge (even when it cuts me). I am relatively familiar with Java itself, but I hate all Java tooling and usually just stick to GNU Make for my own things lmao. Thanks for the info.
