### ISSUE TITLE
Update to 1.20.4

### ISSUE THREAD

**Issue by thiagogebrimm** [SHsuperCM/CITResewn#358]
the mod does not turn on in minecraft 1.20.4

**Comment by TechPro424** [comment]
Bump

**Comment by Nyphet** [comment]
I too would like a port for 1.20.4

**Comment by Pheonix039** [comment]
bump
a 1.20.4 port would be awesome ngl

**Comment by Partyrock4589** [comment]
bump 
really would like this

**Comment by SHsuperCM** [comment]
Please do not open issues to update.

**Comment by masterflitzer** [comment]
well it is an issue, the github feature is designed for this, there is no other mechanisms just for updates, updates are just issues

duplicates I can understand they're annoying, but what's wrong with an issue

you can just close it when it's completed or just let it open if you don't plan to work on it (which is entirely fine it's your repo after all)

**Comment by Thsgun** [comment]
sorry for the dupe pr, however everyone here has been relying on dicedpixel’s fork and i dont believe they are going to continuously update for us, especially when 1.21 comes out.

**Comment by Boobies** [comment]
> well it is an issue, the github feature is designed for this, there is no other mechanisms just for updates, updates are just issues
> 
> duplicates I can understand they're annoying, but what's wrong with an issue
> 
> you can just close it when it's completed or just let it open if you don't plan to work on it (which is entirely fine it's your repo after all)

Tickets are supposed to be useful, not a way to pester maintainers. Issues like this don't help or add any useful information.

**Comment by masterflitzer** [comment]
I'm not talking about duplicates but tracking a version release is common in issue trackers, how is it pestering when i create an issue for supporting 1.21 as soon as it comes out and the maintainer can close the issue with the PR that adds support

besides maintainers don't need to be aware of new releases, so an issue is always good for this

there is no reason to be hostile and tell people they shouldn't create an issue for supporting a new version, that's just stupid and toxic

**Comment by Boobies** [comment]
It's only common in issue trackers because random users insist on filing these tickets who annoy everyone, I can guarantee none of the maintainers actually appreciate them. Some are more vocal about it (like this situation here or JellySquid who scolds the reporter and closes the ticket immediately on projects such as Sodium and Lithium) while others just let it slide.

You seem to be missing the point of issue trackers. In the end, their point is to be helpful. Opening tickets just because you're bored and it's not a such a big deal to close them is not helpful. There are plenty of invalid tickets to go around, don't add to the noise. It's not the sort of thing that slips anyone's mind, people know. Imagine a maintainer 5 years later going "Oh, I thought Minecraft development was halted, oops, didn't think to update."

**Comment by masterflitzer** [comment]
wdym filling with tickets? it's a single issue, why are you so mad, it's entirely valid to have an issue that the latest version isn't supported yet, it's literally an issue with the software (not critical but nonetheless valid), of course it's something that can be overlooked, do you work in software development? developer are busy developing and don't always check if the game has a new version, they don't necessarily play the game, also an issue for a version can be a way to communicate if an update is even planned, like the maintainer can close as not planned if they decide to skip this version, just stop complaining, we don't complain that 1.20.4 isn't supported we just mentioned it so people searching for it know the status also for possible contributors the version progress can be tracked here, like mentioning PRs etc. (not everyone uses milestones and they shouldn't necessarily be about versions)

what really is annoying are these "bump" comments, i could understand that these can piss people off, i agree with that, that's just spam but a single issue about a version update is not spam

**Comment by elencosm** [comment]
they said filing tickets not with tickets

but they are right in that you seem to be rationalizing a position you cannot defend since even the maintainer said he is against it and you keep insisting it is helpful. u can make up arguments on paper for anything but are they true

**Comment by masterflitzer** [comment]
i just messed up the order of the two words "with" and "filing"..., corrected now

none of what you said in your statement makes any sense, i am taking a position and defended it, you might not agree but how is your comment proving i'm wrong? the maintainer saying he doesn't like it is what i called out in the first place, how are you even using this as an argument lmao

uk what's funny? you complaining about how it's not helpful is unhelpful, y'all blew up this issue for no reason, instead of actual maintainers just restricting this issue to collaborators only and let it be, then we would have one tracking issue without all these comments and linked PRs would still be there

it's wild how annoyed you are about a single issue, just sitting there waiting to be completed or closed, just shows how some are unable to use a global dev & collab tool like github

**Comment by SHsuperCM** [comment]
Holy hell, what happened here....
I left this issue open to try and minimize the amount of people opening new issues about it, if not for that this would've been closed as this is not the place to pest about this sort of thing. 

This is not an issue, you are asking for support on a version of the game that is not supported yet. Asking devs to port has no place in github issues.

Apologies for not locking this sooner.
