### ISSUE TITLE
Server Resource Pack does not take priority.

### ISSUE THREAD

**Issue by Sorvent** [SHsuperCM/CITResewn#359]
Hello! First time posting on github, please bear with me if there are any issues with my post. I have a very unique issue pertaining to the server hoplite,gg

The servers custom textures do not take precedent despite being higher on the list in priority in the resource pack folder. I am propsiing one of two possible solutions:
1. Add an exclusion condition to exclude specific items from having a CIT texture applied to them
2. Allowing Servers to take precedent (I have no idea if this is even possible)

How to repeat the issue:
1. Create a Custom Item Texture for a Diamond Sword with Sharpness 1
2. Log into hoplite,gg, open the recipe book and compare the texture for "Midas Sword".

Attached are the relevant screenshots. Thank you!
![image_2023-12-12_195211591](https://github.com/SHsuperCM/CITResewn/assets/153697947/c03166a5-275b-4cc4-bc76-2e1bcc94e858)
![2023-12-12_19 36 14](https://github.com/SHsuperCM/CITResewn/assets/153697947/2a0d9432-81c5-4721-aaa5-6eff9d83fc5a)
![2023-12-12_19 39 26](https://github.com/SHsuperCM/CITResewn/assets/153697947/81917e46-a0fa-4146-9088-e6be3aa8aab6)

**Comment by SHsuperCM** [comment]
Apologies but this is exactly by design that it does that. CITs do not behave like other resources with vanilla pack layering, they have their own priority system that dictate how they are applied after all resourcepacks are done.

To revert to having the sword that's in the server pack, you'd have to have a higher priority CIT(either in the server pack or in a separate client pack) decide what to do with the specific item.

**Comment by Sorvent** [comment]
I dont believe that the server actually uses CIT layering, as these textures are visible on a Vanilla client. This works perfectly fine on a regular optifine instance.

**Comment by SHsuperCM** [comment]
Yes. Exactly as I said, CITs are on one level over resourcepack ordering. They are _supposed_ to override what the server is doing in its resourcepack.
