### ISSUE TITLE
Publish releases on GitHub Releases

### ISSUE THREAD

**Issue by NatoBoram** [SHsuperCM/CITResewn#37]
It would be nice to be able to downloads releases from the [Releases](https://github.com/SHsuperCM/CITResewn/releases) tab

**Comment by SHsuperCM** [comment]
Haven't thought of that because I dont want end users downloading from github. But if other mods add dependencies to it with jitpack I guess I could also put versions in the releases when I upload them to modrinth. Still, I do not recommend looking in here for releases, try to use modrinth when possible.
