### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by HiWord9** [SHsuperCM/CITResewn#387]
Latest 1.1.5-1.20.4 jar on modrinth marked as v1.1.5 but inside it says it is v1.1.4
![image](https://github.com/SHsuperCM/CITResewn/assets/46609661/29aa0ad5-e695-4591-8d02-e72b4db78596)
![2024-04-01_22 23 15](https://github.com/SHsuperCM/CITResewn/assets/46609661/961c1472-b910-4835-80f6-2c10eef9d443)

The same with cit defaults
![image](https://github.com/SHsuperCM/CITResewn/assets/46609661/b030de43-53c5-4e5f-aa18-5ee13867ba0a)

**Comment by SHsuperCM** [comment]
Oh this is very odd, inspecting the classes it actually is v1.1.5 but only the version in the json didnt change and only on 1.20.4.

To keep on record, this issue is both on modrinth's and on curseforge's version so it's not something specific to modrinth.

As I cant really replace the files that are uploaded this will just get resolved in the next update but I will definitely keep an eye on it. Thanks for letting me know!

**Comment by SHsuperCM** [comment]
Ah, found the issue. Versions going forward will be fixed
