### ISSUE TITLE
Crash after clicking "Configure"

### ISSUE THREAD

**Issue by Fate-EX** [SHsuperCM/CITResewn#4]
CIT Resewn doesn't seem to recognize this resource pack
GearsPlus 1.17
https://www.planetminecraft.com/texture-pack/vanilla-more-items-armor-shields-and-more/

P.S. There's a configure button for CIT Resewn on the Fabric API where clicking it leads to a "saving world" screen before CTD.

**Comment by SHsuperCM** [comment]
CTD?

**Comment by Fate-EX** [comment]
Crash to desktop, well, the Minecraft launcher in this case.

**Comment by SHsuperCM** [comment]
Can you provide the log file after the crash?

**Comment by SHsuperCM** [comment]
I'm on my phone right now so I'll check it out when I get a chance.

For the resourcepack tho, the pack itself is the problem, under optifine/cit it contains folders with spaces in their names which are not allowed ever since pack_format 3.
The pack works on Optifine because it has invasive and awful changes which remove that restriction.
I will not do that in CIT Resewn.

See issue #3.


I will be leaving this issue open for the crash but its subject will no longer be about the resourcepack in question.

**Comment by SHsuperCM** [comment]
@Fate-EX 
Apologies for the delay, had some stuff come up. 
Looking through the crash traces there is nothing to do with CIT Resewn that would've caused this. 
The crash seems to be caused by cloth config. I then noticed you are running "cloth-config2@4.7.0-unstable" while I am running "cloth-config2@5.0.38".
Please try updating cloth config and reopen the issue if the bug presists.

**Comment by SHsuperCM** [comment]
After much consideration and a suggestion that was given in #9, I've decided to allow broken paths and block it behind both a config option that defaults to not allow broken paths as well as mark the packs incompatible in the resourcepack selection screen.

This has been implemented in [v0.5.0](https://modrinth.com/mod/cit-resewn/version/6JfMqtLA).

Still this is very experimental and no bugs that derive from the config option being enabled will be resolved.
