### ISSUE TITLE
Temperary patch for 1.20.6

### ISSUE THREAD

**Issue by DonFlymoor** [SHsuperCM/CITResewn#406]
For now you could take the new conditions and parse them into the old NBT format when applying textures and models, so as not to break compatibility with old resource packs. This would be a relatively simple patch and would allow the mod to continue to work until a decision is reached in https://github.com/sp614x/optifine/issues/7658

**Comment by shadowtigercool** [comment]
any update on this?

**Comment by Mukul1127** [comment]
This is a good idea

**Comment by STICKzilla21** [comment]
Something like this?
```
type=item
matchItems=name_tag
nbt.custom_name=Dinnerbone
```

**Comment by Mukul1127** [comment]
I think he means to basically ignore the new conditions and instead parse the old ones so older stuff will still work

**Comment by SHsuperCM** [comment]
The problem is that there is no new format decided yet. If anything `nbt.` is going away and will be replaced with actual components support. Porting between the two however is not a simple task and would most likely break a lot of resourcepacks which is what I am debating on doing.
I'd much rather see optifine spec before moving forwards with this port as the situation is very complicated.

Just be patient.
