### ISSUE TITLE
Not compatible with 1.17

### ISSUE THREAD

**Issue by Smolax** [SHsuperCM/CITResewn#41]
The site says that the mod is compatible with 1.17 and 1.17.1, however this is not the case...
![image](https://user-images.githubusercontent.com/23561451/134940615-6b06b219-c2b0-4b05-9616-27b0d37af580.png)

**Comment by SHsuperCM** [comment]
I listed the mod with 1.17 because a lot of people click 1.17 when they filter mods on Curse, iirc it wouldn't find 1.17.1 mods if you did it like that.

The fix will be out in a future version as this is really trivial. If you really need it to launch in 1.17, open the jar and change `fabric.mod.json` to have 
```json
    "minecraft": "1.17.x"
```
instead of "1.17.1".

Either way, you should be using 1.17.1.
