### ISSUE TITLE
Backport to 1.16.5

### ISSUE THREAD

**Issue by superloach** [SHsuperCM/CITResewn#48]
I know it's a lot of work to maintain two versions, so it's alright if you don't want to do this.

Unfortunately, I'm not too familiar with Fabric, or even Java, otherwise I'd try to do this myself.

I attempted changing the versions in the `gradle.properties`, and got these errors: https://termbin.com/6pn2.

**Comment by SHsuperCM** [comment]
This is already being considered but right now I want to get the mod out and add the extra features I already had in mind for it.

The build is failing because in addition to building against a different version, I'd also need to remap the references in the code to match 1.16 and probably also fix the bugs that come with that.

Once CIT Resewn is in a place where I'm comfortable releasing it as release versions I am looking to support 1.16-1.18 and keep the most recent versions supported but for now I'll keep it only for the version I'm actively playing so that I can spot bugs more easily.

**Comment by SHsuperCM** [comment]
Apologies but I was not aware of how hostile 1.16 was to the current implementation of the mod. This is not just a simple remap because a lot of the internal things CIT Resewn needs in order to work properly have not been added to the game yet and releasing the port without feature parity between the version is not something I want to do here. 

My original plan was to keep the mod updated in versions 1.16-1.18 but now I cannot promise 1.16 as it takes too much time away from the development of more relevant versions.

I might find the time in the future to backport it but as of right now, this is not a trivial task and requires rewriting 2 big chunks of code which I do not have the capacity to do so at this point.

CIT Resewn's main focus will always be the latest versions and while 1.16 is not that old, the internal changes that 1.17 brought make it really different.

If anyone else wants to attempt backporting it, be my guest.

**Comment by superloach** [comment]
No worries at all! I'm no longer interested in running this on 1.16 anyway, I'll try it out on 1.18 tonight :)

**Comment by UnFierrito** [comment]
please make it for 1.16.5  😟

**Comment by SHsuperCM** [comment]
Conversation regarding backports is now moved to issue #120.
