### ISSUE TITLE
Lore does not seem to be working

### ISSUE THREAD

**Issue by mitchngwen** [SHsuperCM/CITResewn#60]
The lore line is  "Stored: 2,669 / 6,400 (41.7%)"  //This line changes based on how many items you have inside the block.//

//so I'm trying to use this line for anything at 40%, if that makes any sense.//
nbt.display.Lore.0=Stored: * / * (4*

**Comment by SHsuperCM** [comment]
So what you're doing there is checking a literal but it looks like you want to use a pattern based on the asterisks.

```.properties
nbt.display.Lore.0=Stored: * / * (4*
```
Checks literally `Stored: * / * (4*`

To check for a pattern that has wildcards you need to prefix it with `pattern:` like so:
```.properties
nbt.display.Lore.0=pattern:Stored: * / * (4*
```

Now that'll work but the pattern you have there will also match 4%. If you dont mind that it's fine but you 
might want to instead check for a regex to see that it's actually what you're targetting.

You can use regex by prefixing `regex:` instead of pattern and you can look up how to use regex online.

This section in the docs is relevant and if you have any more questions feel free to ask.
https://citresewn.readthedocs.io/cit/cit_base/#nbt-match

**Comment by mitchngwen** [comment]
That did the trick! You are one of the best Devs that I have talked to, very helpful. Thank you.
