### ISSUE TITLE
Does not appear to work for sphax extra optifine

### ISSUE THREAD

**Issue by Remyzk** [SHsuperCM/CITResewn#71]
The mod does not appear to be working with the extra optifine addon for sphax, although it may just be a conflic with another mod I am using:
Sodium
Lithium
Phosphor
Indium
Continuity
LambaBetterGrass
CitResewn
Mod Menu
Cloth Config
Fabric Api

**Comment by SHsuperCM** [comment]
I'm assuming you mean [BDCraft's ExOf](https://bdcraft.net/downloads/purebdcraft-minecraft/exof-addon/) resource pack when you say sphax extra optifine?
If not, please link the pack.

**Comment by Remyzk** [comment]
Yeah sorry I should've linked the pack, it is that exact one

**Comment by SHsuperCM** [comment]
Right. What's happening here is that the exof pack uses things from BDCraft itself. Cross resourcepack cits are not supported due to the nature of CIT Resewn's implementation. By definition, CIT Resewn allows cits to use assets only from their own packs. I might add support for cross-pack assets in the future but it is not planned currently.

For now if you want to use the pack you could (probably™) just merge exof's `assets` into BDCraft's `assets` and the cits should work. I dont really know why they wouldnt do that in the first place as exof adds nothing but small text files.

Also, next time instead of listing your mods, you should upload a log file which gives mod authors a lot more information such as a full list of mods, exact fabric/mod versions, loading errors, debug info, etc..
