### ISSUE TITLE
Models file path disparity

### ISSUE THREAD

**Issue by xalixilax** [SHsuperCM/CITResewn#79]
I've been creating texture pack with optifine for quite a while and got used to all it's jankyness, but recently started to get away from it especially because of Optifabric not working properly recently. 

Anyway I created some barrels CTM and CIT. I use a model that is located in the same folder as the properties and it is used properly. My issue is that inside that model, one of the texture is placed in my CTM folder and for some reason, it can't fetch it when using CITResewn. 

Here is my model
`{
  "parent": "minecraft:block/cube_column",
  "textures": {
    "end": "minecraft:block/acacia_planks",
    "side": "assets/minecraft/optifine/ctm/bookshelf/acacia/acacia_bookshelf"
  }
}`

I tried different path but didn't managed to make it work. I tried to move it inside minecraft:block/.. And it worked but it broke my CTM. My goal is to have only one image for both CTM and CIT so it's easier to modify and I'd like to not have to move anything since I have many textures, especially for the barrels

If you want to try the pack by yourself and test it out, here is the download link:
https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla

Thank you. If you have a discord, sometime it could be easier to discuss. Just let me know.

https://www.mediafire.com/view/mppadwzwb373llw
https://www.mediafire.com/view/jovblobqj8ok100

**Comment by SHsuperCM** [comment]
I swear, if there's one more undocumented thing optifine does I'm gonna lose it.

Right now the only way CITResewn modifies the jsons it loads is if the texture path starts with a `./` for relative paths because that seems like a common thing people do with all of the one cit's files in a single folder.

I'll get around to making it resolve the textures regardless and that should allow it to find absolute paths.

**Comment by SHsuperCM** [comment]
Will be fixed in v0.8.2
