### ISSUE TITLE
Crash with Fabric API 0.46+

### ISSUE THREAD

**Issue by DelofJ** [SHsuperCM/CITResewn#99]
When you launch Minecraft with CIT Resewn and Fabric API with a version starting by 0.46, the game crashes on both 1.17.1 and 1.18.1, I tested Minecraft 1.17.1 with CIT Resewn 0.9.1 and Fabric API 0.46.1, and Minecraft 1.18.1 with CIT Resewn 0.9.1 and Fabric API 0.46.3

**Comment by SHsuperCM** [comment]
Tested with 0.46.3+1.18 and 0.46.1+1.17.
Does not seem to crash and CITs are loading fine.. There should not be anything different between 45 and 46 with fapi's usage.

**Comment by SHsuperCM** [comment]
I'm marking as invalid and the issue could be reopened once you provide logs.

**Comment by DelofJ** [comment]
Hi, here is the [latest.log](https://gist.github.com/DelofJ/b8a1bcd1978c417b3008dfa0c5fc678a) and the [crashlog](https://gist.github.com/DelofJ/a9338e08293b9ee339a889849c3f466e)

**Comment by SHsuperCM** [comment]
Where are you getting fabric api from?

**Comment by SHsuperCM** [comment]
It's launching fine for me with the exact same versions and fabric api from [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3634318).

Your logs say that the base fabric api loaded but none of the actual fapi modules did.
[The crash is caused because the command api module is missing.](https://gist.github.com/DelofJ/a9338e08293b9ee339a889849c3f466e#file-crash-2022-02-03_19-17-38-client-txt-L22)

**Comment by DelofJ** [comment]
I downloaded it from the CurseForge page
Update: After downloading the Fabric API again, everything worked fine, after comparing the 2 files, I realized that the other file was missing some stuff when I opened it with WinRAR
Sorry for the inconvenience 😅
